name: mausam
description: A simple weather app.

version: 1.0.0+1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_dotenv: ^2.1.0
  geolocator: ^6.1.10
  google_fonts: ^0.3.10
  intl: ^0.16.1
  provider: ^4.0.4
  weather_icons: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - .env
  fonts:
    - family: FredokaOne
      fonts:
        - asset: assets/fonts/FredokaOne-Regular.ttf
